---
- name: install latest version of nginx
  hosts: all
  become: yes
  become_user: root

  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: latest
 
  - name: start nginx
    service:
      name: nginx
      state: started
