---
- name: install and configure Apache
  hosts: web
  become: yes
  become_user: root

  vars:
    become_ansible_pass: "vagrant"

  tasks:
    - name: stop httpd 
      ansible.builtin.service:
        name: httpd
        state: stopped
    
    - name: remove index.html
      file: 
        path: /var/www/html/index.html
        state: absent       

    - name: uninstall httpd
      ansible.builtin.yum:
        name: httpd
        state: absent 

...
