---
# tasks file for php
- name: install php
  ansible.builtin.yum:
    name:
      - php
      - php-mysqlnd
      - php-common
    state: present

- name: restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: copy info.php
  ansible.builtin.copy:
    src: info.php
    dest: /var/www/html/info.php

